config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"

  resources :cocktails, except: [:index] do
    resources :doses, except: [:destroy]
  end

  delete "doses/:id", to: "doses#destroy", as: :dose
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
  has_one :user

  validates :name, uniqueness: true, presence: true
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktails, only: [:edit, :destroy, :show, :update]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @cocktails = policy_scope(Cocktail).order(created_at: :desc).where("name ILIKE ?", "%#{params[:query]}%")
    else
      @cocktails = policy_scope(Cocktail).order(created_at: :desc)
    end
  end

  def new
    @cocktail = Cocktail.new
    authorize @cocktail
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    authorize @cocktail
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @dose = Dose.new
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def find_cocktails
    @cocktail = Cocktail.find(params[:id])
    authorize @cocktail
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo).to_h.merge(user_id: current_user.id)
  end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/edit.html.erb
<div class="container" style="margin-top: -120px;">
  <div class="row">
    <div class="col-md-12" style="margin-top: 200px;">
      <div class="wrapper-show">
        <div class="wrapper-edit-link">
          <%= link_to edit_cocktail_path(@cocktail) do  %>
            <i class="fas fa-pencil-alt"></i>
          <% end %>
        </div>
        <div class="wrapper-header">
          <%= simple_form_for(@cocktail, defaults: { input_html: { class: "form-text" }, label_html: { class: "form-text" } }) do |f| %>
          <div class="row">
            <div class="col-4">
              <h1><%= @cocktail.name %></h1>
                    <%= f.input :name %>
            </div>
            <div class="col-8">
              <% if @cocktail.photo.attached? %>
                <div class="wrapper-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key, width: 400, height: 300, crop: :fill %>')">
                </div>
                  <%= f.input :photo, as: :file %>
                  <%= f.submit "Submit changes", class: "button" %>
              <% else %>
                <div class="wrapper-img" style="filter: grayscale(100%);background-color: black">
                </div>
                   <%= f.input :photo, as: :file %>
                   <%= f.submit "Submit changes", class: "button" %>
                   <% end %>
              <% end %>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1547059470-3b0c7cd958a4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1651&q=80);">
  <h1>Awesome Cocktails</h1>
</div>
<div class="contain">
  <div class="flex">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-6 col-lg-4">
      <% if cocktail.photo.attached? %>
      <div class="cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, width: 400, height: 300, crop: :fill %>')">
        <div class="card-category"><%= cocktail.name %></div>
        <div class="card-description">
          <p><%= cocktail.doses.map { |dose| dose.ingredient.name }.join(", ") %></p>
        </div>
      </div>
      <%= link_to cocktail_path(cocktail) do %>
      <div class="card-link"></div>
      <% end %>
      <% else %>
      <div class="cards" style="filter: grayscale(100%);background-color: black;">
        <div class="card-category"><%= cocktail.name %></div>
        <div class="card-description">
          <p><%= cocktail.doses.map { |dose| dose.ingredient.name }.join(", ") %></p>
        </div>
      </div>
      <%= link_to cocktail_path(cocktail) do %>
      <div class="card-link"></div>
      <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
  <div class="form-box">
    <h1>Add your cocktail</h1>
    <%= simple_form_for(@cocktail, defaults: { input_html: { class: "form-text" }, label_html: { class: "form-text" } }) do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "New Cocktail", class: "button" %>
    <% end %>
  </div>

app/views/cocktails/show.html.erb
<div class="container" style="margin-top: -120px;">
  <div class="row">
    <div class="col-md-12" style="margin-top: 200px;">
      <div class="wrapper-show">
        <div class="wrapper-edit-link">
          <%= link_to edit_cocktail_path(@cocktail) do  %>
            <i class="fas fa-pencil-alt mr-4"></i>
          <% end %>
          <%= link_to cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure?" } do  %>
            <i class="fas fa-trash"></i>
          <% end %>
        </div>
        <div class="wrapper-header">
          <div class="row">
            <div class="col-4">
              <h1><%= @cocktail.name %></h1>
            </div>
            <div class="col-8">
              <% if @cocktail.photo.attached? %>
                <div class="wrapper-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key, width: 400, height: 300, crop: :fill %>')">
                </div>
              <% else %>
                <div class="wrapper-img" style="filter: grayscale(100%);background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path("jkh7kyurtohmrj3dmjgl", width: 400, height: 300, crop: :fill) %>')">
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="container wrapper-grey dose-display rounded">
          <div class="row mt-4 pt-2">
            <div class="col-1">
              <h3><br></h3>
            </div>
            <div class="col-4">
              <h3>Ingredients</h3>
            </div>
            <div class="col-4">
              <h3>Amount</h3>
            </div>
          </div>
            <% @cocktail.doses.each do |dose| %>
          <div class="row">
            <div class="col-1">
             <%= link_to dose_path(dose.id), method: "delete", class: "button-remove" do  %>
               <i class="fas fa-minus"></i>
             <% end %>
            </div>
            <div class="col-4 p-display">
              <p><%= dose.ingredient.name  %></p>
            </div>
            <div class="col-4 p-display ">
              <p><%= dose.amount  %></p>
            </div>
          </div>
          <% end %>
          <%= simple_form_for [@cocktail, @dose], class: "input" do |f| %>
          <div class="row mt-4">
            <div class="col-1">
              <%= button_tag(type: 'submit', class: "button-add") do %>
                <i class="fas fa-plus"></i>
              <% end %>
            </div>
            <div class="col-4">
              <h3><%= f.association :ingredient, label: false %></h3>
            </div>
            <div class="col-4 amount-input" style="display: inline;">
              <h3><%= f.input :amount, as: :string, label: false %></h3>
            </div>
          </div>
           <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>